trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  aksTest: 'clu-demo'
  aksTestRG: 'rg-clu-demo'
  aksTestIP: 'clu-demo-ip'
  gitURL: 'gbaeke/demo-clu-flux'

stages:
- stage: DeployDemoCluster
  jobs:
  - job: 'OneBigJob'
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    # DEPLOY AKS IN TEST   
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'AzureMPN'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(aksTestRG)'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'aks/deploy.json'
        csmParametersFile: 'aks/deployparams.t.json'
        # overrideParameters: '-serverAppSecret $(serverAppSecret) -clientIdsecret $(clientIdsecret) -clusterName $(aksTest)'
        overrideParameters: '-clusterName $(aksTest) -clientIdsecret $(clientIdsecret)'
        deploymentMode: 'Incremental'
        deploymentName: 'aks-deploy'
    # DEPLOY IP ADDRESS IN BACKING RESOURCE GROUP
    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'AzureMPN'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'MC_rg-clu-demo_clu-demo_westeurope'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: 'ip/deploy.json'
        overrideParameters: '-ipName $(aksTestIP)'
        deploymentMode: 'Incremental'
        deploymentName: 'aksTestIp'
        deploymentOutputs: 'armoutputs'
    - task: Bash@3
      name: GetIP
      inputs:
        targetType: 'inline'
        script: |
          echo "##vso[task.setvariable variable=test-ip;]$(echo '$(armoutputs)' | jq .ipaddress.value -r)"
    
    # INSTALL KUBECTL
    - task: KubectlInstaller@0
      name: InstallKubectl
      inputs:
        kubectlVersion: '1.14.8'

    #INSTALL HELM v3
    - task: HelmInstaller@1
      name: InstallHelmv3
      inputs:
        helmVersionToInstall: 'latest'

    # GET CREDS TO K8S CLUSTER WITH ADMIN (required for AAD integrated cluster and Helm)
    - task: AzureCLI@1
      name: RunAzCLIScripts
      inputs:
        azureSubscription: 'AzureMPN'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials -g $(aksTestRG) -n $(aksTest) --admin
          helm repo add stable https://kubernetes-charts.storage.googleapis.com/
          helm repo add fluxcd https://charts.fluxcd.io
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          kubectl apply -f https://raw.githubusercontent.com/fluxcd/helm-operator/master/deploy/flux-helm-release-crd.yaml
          kubectl apply --validate=false -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.12/deploy/manifests/00-crds.yaml
          
    - task: Kubernetes@1
      name: NSfluxcd
      displayName: Create fluxcd namespace
      inputs:
        connectionType: 'None'
        command: 'apply'
        useConfigurationFile: true
        configurationType: 'inline'
        inline: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: fluxcd
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'

    - task: Kubernetes@1
      name: NScertmanager
      displayName: Create cert-manager namespace
      inputs:
        connectionType: 'None'
        command: 'apply'
        useConfigurationFile: true
        configurationType: 'inline'
        inline: |
          apiVersion: v1
          kind: Namespace
          metadata:
            name: cert-manager
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'

    # DEPLOY NGINX INGRESS
    - task: HelmDeploy@0
      name: nginx
      displayName: Install nginx Ingress Controller
      inputs:
        connectionType: 'None'
        namespace: 'kube-system'
        command: 'upgrade'
        chartType: 'Name'
        chartName: 'stable/nginx-ingress'
        releaseName: 'nginx'
        overrideValues: 'controller.service.loadBalancerIP=$(test-ip),controller.publishService.enabled=true,controller.metrics.enabled=true'
        arguments: '--timeout 20m0s'
        

    # DEPLOY EXTERNAL DNS
    - task: HelmDeploy@0
      name: ExternalDNS
      displayName: Install External DNS with CloudFlare baeke.info
      inputs:
        connectionType: 'None'
        namespace: 'kube-system'
        command: 'upgrade'
        chartType: 'Name'
        chartName: 'stable/external-dns'
        releaseName: 'externaldns'
        overrideValues: 'cloudflare.apiToken=$(CFAPIToken)'
        valueFile: 'externaldns/values.yaml'

     # DEPLOY HELM OPERATOR
    - task: HelmDeploy@0
      name: HelmOp
      displayName: Install Flux CD Helm Operator
      inputs:
        connectionType: 'None'
        namespace: 'kube-system'
        command: 'upgrade'
        chartType: 'Name'
        chartName: 'fluxcd/helm-operator'
        releaseName: 'helm-operator'
        overrideValues: 'extraEnvs[0].name=HELM_VERSION,extraEnvs[0].value=v3,image.repository=docker.io/fluxcd/helm-operator-prerelease,image.tag=helm-v3-dev-53b6a21d'
        arguments: '--namespace fluxcd'

    - task: HelmDeploy@0
      name: FluxCD
      displayName: Install Flux CD
      inputs:
        connectionType: 'None'
        namespace: 'fluxcd'
        command: 'upgrade'
        chartType: 'Name'
        chartName: 'fluxcd/flux'
        releaseName: 'flux'
        overrideValues: 'git.url=git@github.com:$(gitURL),git.pollInterval=1m'

    - task: HelmDeploy@0
      name: certmanager
      inputs:
        connectionType: 'None'
        namespace: 'cert-manager'
        command: 'upgrade'
        chartType: 'Name'
        chartName: 'jetstack/cert-manager'
        releaseName: 'cert-manager'
        arguments: '--version v0.12.0'

